/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBreadcrumbs: typeof import('./src/components/AppBreadcrumbs.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    ChatNotificationFloat: typeof import('./src/components/ChatNotificationFloat.vue')['default']
    ChatSettings: typeof import('./src/components/ChatSettings.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    GlobalLoader: typeof import('./src/components/GlobalLoader.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StationEditor: typeof import('./src/components/StationEditor.vue')['default']
    ThemeCustomizer: typeof import('./src/components/ThemeCustomizer.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    TiptapEditor: typeof import('./src/components/TiptapEditor.vue')['default']
  }
}
